### ISSUE TITLE
Polygon query on visible layers only

### ISSUE THREAD

**Issue by PACrausaz** [camptocamp/GeoMapFish#35]
### Who requested this new feature?

Pierre-André Crausaz, Canton du Jura
### Is your feature request related to a problem?
Yes
The query works on layer even if the layer is not visible, which is confusing for the user. 

### Describe the solution you'd like
Query should consider only visible layers .

**Comment by rbovard** [comment]
Hi @PACrausaz 

Could you please provide a link to repdroduce?

I just tested here and this bug is not present.

**Comment by PACrausaz** [comment]
Rémi,
On this view, the query returns cadastral informations which are not visible: 
https://geo.jura.ch/s/XPB7

**Comment by gnerred** [comment]
@PACrausaz , it's a wrong behaviour that will be fixed in version 2.6 : 

2.6.53 : Scale limit on WMTS query
