### ISSUE TITLE
dd disclaimer on LayerGroups

### ISSUE THREAD

**Issue by remyguillaume** [camptocamp/GeoMapFish#37]
### Who requested this new feature?
> *name, canton, city, company, ...*

### Is your feature request related to a problem?
> *Yes or No*
> *If Yes, a clear and concise description of what the problem is.*

### Describe the solution you'd like
> *A clear and concise description of what you want.*

### Additional information or points to watch out for
> *Any other information or screenshot about this feature request.*
> *Any point to watch out for or open question*

**Comment by rbovard** [comment]
?

**Comment by svareg** [comment]
Hum... I don't know what happed.
The right ticket is here : https://github.com/camptocamp/GeoMapFish/issues/38

This one has been saved, but shouldn't have...
I'm closing this one
