### ISSUE TITLE
Disclaimer support WMTS layer groups

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/GeoMapFish#44]
### Who requested this new feature?
> cartoriviera

### Is your feature request related to a problem?
> Yes

To test: 

1°/ Add a disclaimer on a WMTS layer group
2°/ Go to interface and activate some layers of the group -> no disclaimer displays

### Describe the solution you'd like
Add support of this case

See also: https://jira.camptocamp.com/browse/GSGMF-1364

**Comment by pfanguin** [comment]
Same issue as https://github.com/camptocamp/GeoMapFish/issues/38
