### ISSUE TITLE
Do not prompt error when activating a layer through the search bar

### ISSUE THREAD

**Issue by ponceta** [camptocamp/GeoMapFish#47]
### Who requested this new feature?
Ville de Pully

### Is your feature request related to a problem?
Yes, an error message appears when activating a layer with a search request when it is already loaded in the left panel but deactivated.

![Error_when_activating_layer](https://user-images.githubusercontent.com/8614223/110338202-07ed3c80-8027-11eb-9df8-37f50636d0b0.gif)

Thinking towards a search based navigation approach.

### Describe the solution you'd like
No error message is prompted

### Additional information or points to watch out for
None

**Comment by maltaesousa** [comment]
@ponceta This is not an error, it has a 'alert-info' class and it's blue by default. I think it's a custom css on your instance that makes it look like an error.

**Comment by maltaesousa** [comment]
@ponceta Closing this as it is a CSS problem on your instance. Feel free to re-open if you think it's a GMF issue
