### ISSUE TITLE
No legend available with external WMS layers

### ISSUE THREAD

**Issue by cimbach** [camptocamp/GeoMapFish#50]
When adding an external WMS layer, there is only the trashcan icon next to it in the layer tree. The gear icon is missing and thus the legend as well.

Example on cartoriviera website with a WMS layer from the Canton de Vaud.
https://map.cartoriviera.ch/s/p6jBS
![no_legend](https://user-images.githubusercontent.com/6229242/118813140-22595700-b8af-11eb-8d65-db8e4de4adb7.png)

Same layer added to GMF 1.6 where the legend is available:
https://map.lausanne.ch/prod/s/fdLl
![legend](https://user-images.githubusercontent.com/6229242/118813265-40bf5280-b8af-11eb-9c02-455b2850ecbc.png)

**Comment by gnerred** [comment]
This is fixed in GMF 2.6 (Cartoriviera is in GMF 2.5 yet)

**Comment by cimbach** [comment]
Any chance the fix will be applied to GMF 2.5 as well?

**Comment by gnerred** [comment]
It was a feature ordered for 2.6, it is not planned to backport it

**Comment by remyguillaume** [comment]
It's fixed in 2.6, and won't be backported to 2.5.
I'm closing this.
