### ISSUE TITLE
Better behavior when external OGC server is not reachable

### ISSUE THREAD

**Issue by jwkaltz** [camptocamp/GeoMapFish#59]
### Who requested this new feature?
Ralph Schuler, Canton Schwyz

### Is your feature request related to a problem?
Yes:
when an OGC server is configured that refers to an external URL, such as https://geodienste.ch, and that URL is not reachable, then the whole GMF geoportal does not load anymore.

### Describe the solution you'd like
When an external service such as https://geodienste.ch used as a OGC server is down, only the layers from that OGC server should be unavailable. All other layers should work as usual.

**Comment by remyguillaume** [comment]
Same with WMTS : https://github.com/camptocamp/GeoMapFish/issues/22

**Comment by remyguillaume** [comment]
Hi @jwkaltz,

Can you explain what is the difference with the following issue : https://jira.camptocamp.com/browse/GSGMF-1694 (that was solved)

**Comment by jwkaltz** [comment]
> Hi @jwkaltz,
> 
> Can you explain what is the difference with the following issue : https://jira.camptocamp.com/browse/GSGMF-1694 (that was solved)

Thanks for the update @remyguillaume , indeed as I understand this situation has been solved starting GMF 2.6.
