### ISSUE TITLE
Display a scrollbar in the baselayer selector if necessary

### ISSUE THREAD

**Issue by rbovard** [camptocamp/GeoMapFish#8]
### Who requested this new feature?
Rémi Bovard, Ville de Nyon

### Is your feature request related to a problem?
Yes

When the baselayer list is too big, we cannot chose the first layers:
![image](https://user-images.githubusercontent.com/4549666/86584037-95522b80-bf84-11ea-9c60-cccc4322ce30.png)

### Describe the solution you'd like:
Define a dynamic max height for the baselayer selector and display a scrollbar if necessary.

### Additional informations or points to watch out for:
The scrollbar could be in the same style that in the layertree:
![image](https://user-images.githubusercontent.com/4549666/86584641-7ef89f80-bf85-11ea-9637-a3c79e5d98c4.png)

**Comment by rbovard** [comment]
Nice, don't you want to make a PR directly in GMF?

**Comment by rbovard** [comment]
I guess it's a good candidate.

What do you think @pfanguin, is it done in a proper way or it's too "hacky"?

**Comment by pfanguin** [comment]
@rbovard Yes I think it can be integrated for the 2.8. I don't test with all devices and I don't know if it's the official way !

**Comment by maltaesousa** [comment]
Already implemented since 2.6
